/**
 * Coverage for the real, `imaging.ts`-backed `ImageVisionClient`
 * implementation (ticket 004-002, completes the `image-generation-
 * service.md` issue): `server/src/agent/realImageVisionClient.ts`'s
 * `createRealImageVisionClient`.
 *
 * Every test here injects `options.generateImage` (a fixture-returning
 * stand-in for `services/imaging.ts`'s `generateImage`) -- no real
 * network call is ever attempted and no API key is ever read, matching
 * this sprint's convention (`imaging.test.ts`).
 *
 * All filesystem assertions run against a scratch `WORKSPACE_DIR` (a
 * per-run temp directory), never the real `server/workspace/` tree. All
 * DB assertions run against the real test database, cleaned up in
 * `afterAll`.
 */
import fs from 'fs/promises';
import os from 'os';
import path from 'path';
import { prisma } from '../../server/src/services/prisma';
import { resolveWorkspacePath } from '../../server/src/services/workspaceDirectorySync';
import { createRealImageVisionClient } from '../../server/src/agent/realImageVisionClient';
import type { VersioningRecorder } from '../../server/src/agent-mcp/fsTools';
import type { GenerateImageResult as ImagingGenerateImageResult } from '../../server/src/services/imaging';

const marker = `t004rivc${Date.now()}`;

let testRoot: string;
let previousWorkspaceDir: string | undefined;

let ownerId: number;

const cleanup = {
  iterationIds: [] as number[],
  projectIds: [] as number[],
};

/** A `VersioningRecorder` spy: records every path passed to
 * `recordChange` without touching git or the real singleton. */
function spyVersioning(): VersioningRecorder & { calls: string[] } {
  const calls: string[] = [];
  return {
    calls,
    recordChange(p: string) {
      calls.push(p);
    },
  };
}

function fixtureImage(bytes: string): ImagingGenerateImageResult {
  return { bytes: Buffer.from(bytes), model: 'gpt-image-2', size: '1024x1024', quality: 'high' };
}

beforeAll(async () => {
  testRoot = await fs.mkdtemp(path.join(os.tmpdir(), 'flyerbot-real-image-vision-client-test-'));
  previousWorkspaceDir = process.env.WORKSPACE_DIR;
  process.env.WORKSPACE_DIR = testRoot;

  const owner = await prisma.user.create({
    data: { email: `${marker}-owner@example.com`, displayName: 'Real Image Vision Client Test Owner' },
  });
  ownerId = owner.id;
});

afterAll(async () => {
  await prisma.iteration.deleteMany({ where: { id: { in: cleanup.iterationIds } } });
  await prisma.project.deleteMany({ where: { id: { in: cleanup.projectIds } } });
  await prisma.user.deleteMany({ where: { id: ownerId } });

  if (previousWorkspaceDir === undefined) {
    delete process.env.WORKSPACE_DIR;
  } else {
    process.env.WORKSPACE_DIR = previousWorkspaceDir;
  }
  await fs.rm(testRoot, { recursive: true, force: true });
});

afterEach(async () => {
  await prisma.lock.deleteMany({ where: { resourceType: 'directory' } });
});

async function makeProject(title: string) {
  const project = await prisma.project.create({ data: { title, ownerUserId: ownerId } });
  cleanup.projectIds.push(project.id);
  await fs.mkdir(resolveWorkspacePath(`projects/${project.id}`), { recursive: true });
  return project;
}

// ---------------------------------------------------------------------------
// prompt -> file -> Iteration row (AC3)
// ---------------------------------------------------------------------------

describe('createRealImageVisionClient -- generateImage', () => {
  it('writes the generated bytes to a real file and records a matching Iteration row', async () => {
    const project = await makeProject(`${marker}-basic-project`);
    const versioning = spyVersioning();
    const generateImage = vi.fn().mockResolvedValue(fixtureImage('fixture-png-bytes-1'));

    const client = createRealImageVisionClient({ generateImage, versioning });
    const result = await client.generateImage({ prompt: 'a robot mascot postcard', projectId: project.id });
    cleanup.iterationIds.push(
      (await prisma.iteration.findFirst({ where: { projectId: project.id } }))!.id
    );

    expect(result.imagePath).toBe(`projects/${project.id}/iterations/iter-1.png`);

    const written = await fs.readFile(resolveWorkspacePath(result.imagePath));
    expect(written.equals(Buffer.from('fixture-png-bytes-1'))).toBe(true);

    const iteration = await prisma.iteration.findFirst({ where: { projectId: project.id } });
    expect(iteration).toMatchObject({
      seq: 1,
      imagePath: result.imagePath,
      promptUsed: 'a robot mascot postcard',
    });

    expect(generateImage).toHaveBeenCalledTimes(1);
    expect(generateImage.mock.calls[0][0]).toMatchObject({
      prompt: 'a robot mascot postcard',
      size: '1024x1024',
    });

    expect(versioning.calls).toHaveLength(1);
  });

  it('defaults size to 1024x1024 but honors an explicit modelParams.size', async () => {
    const project = await makeProject(`${marker}-size-project`);
    const generateImage = vi.fn().mockResolvedValue(fixtureImage('fixture-png-bytes-size'));

    const client = createRealImageVisionClient({ generateImage, versioning: spyVersioning() });
    const result = await client.generateImage({
      prompt: 'a tall postcard',
      projectId: project.id,
      modelParams: { size: '1024x1536' },
    });
    cleanup.iterationIds.push(
      (await prisma.iteration.findFirst({ where: { projectId: project.id } }))!.id
    );

    expect(generateImage.mock.calls[0][0]).toMatchObject({ size: '1024x1536' });
    expect((result.modelParams as any).size).toBe('1024x1024'); // fixtureImage always reports 1024x1024 back
  });

  it('passes referenceImages/background through from modelParams', async () => {
    const project = await makeProject(`${marker}-refs-project`);
    const generateImage = vi.fn().mockResolvedValue(fixtureImage('fixture-png-bytes-refs'));

    const client = createRealImageVisionClient({ generateImage, versioning: spyVersioning() });
    await client.generateImage({
      prompt: 'edit this scene',
      projectId: project.id,
      modelParams: { referenceImages: ['/tmp/ref.png'], background: 'transparent' },
    });
    cleanup.iterationIds.push(
      (await prisma.iteration.findFirst({ where: { projectId: project.id } }))!.id
    );

    expect(generateImage.mock.calls[0][0]).toMatchObject({
      referenceImages: ['/tmp/ref.png'],
      background: 'transparent',
    });
  });
});

// ---------------------------------------------------------------------------
// Two sequential calls: increasing seq, never-overwritten (AC4)
// ---------------------------------------------------------------------------

describe('createRealImageVisionClient -- never overwrites a prior iteration (AC4)', () => {
  it('two sequential generateImage calls produce two Iteration rows with increasing seq, and the first file is unchanged after the second call', async () => {
    const project = await makeProject(`${marker}-sequential-project`);
    const generateImage = vi
      .fn()
      .mockResolvedValueOnce(fixtureImage('fixture-png-bytes-first'))
      .mockResolvedValueOnce(fixtureImage('fixture-png-bytes-second'));

    const client = createRealImageVisionClient({ generateImage, versioning: spyVersioning() });

    const first = await client.generateImage({ prompt: 'first image', projectId: project.id });
    const iterationFirst = await prisma.iteration.findFirst({ where: { projectId: project.id, seq: 1 } });
    cleanup.iterationIds.push(iterationFirst!.id);

    const firstBytesBefore = await fs.readFile(resolveWorkspacePath(first.imagePath));
    expect(firstBytesBefore.equals(Buffer.from('fixture-png-bytes-first'))).toBe(true);

    const second = await client.generateImage({ prompt: 'second image', projectId: project.id });
    const iterationSecond = await prisma.iteration.findFirst({ where: { projectId: project.id, seq: 2 } });
    cleanup.iterationIds.push(iterationSecond!.id);

    expect(first.imagePath).not.toBe(second.imagePath);
    expect(iterationFirst!.seq).toBe(1);
    expect(iterationSecond!.seq).toBe(2);

    // The first call's file is byte-identical before and after the second call.
    const firstBytesAfter = await fs.readFile(resolveWorkspacePath(first.imagePath));
    expect(firstBytesAfter.equals(firstBytesBefore)).toBe(true);

    const secondBytes = await fs.readFile(resolveWorkspacePath(second.imagePath));
    expect(secondBytes.equals(Buffer.from('fixture-png-bytes-second'))).toBe(true);

    const all = await prisma.iteration.findMany({ where: { projectId: project.id }, orderBy: { seq: 'asc' } });
    expect(all.map((i: any) => i.imagePath)).toEqual([first.imagePath, second.imagePath]);
  });
});

// ---------------------------------------------------------------------------
// Simulated imaging failure (AC5, UC-006 E1)
// ---------------------------------------------------------------------------

describe('createRealImageVisionClient -- a simulated imaging.generateImage failure (AC5, UC-006 E1)', () => {
  it('propagates the error and adds no new Iteration row; prior iterations are unaffected', async () => {
    const project = await makeProject(`${marker}-failure-project`);
    const generateImage = vi.fn().mockResolvedValue(fixtureImage('fixture-png-bytes-prior'));
    const client = createRealImageVisionClient({ generateImage, versioning: spyVersioning() });

    const prior = await client.generateImage({ prompt: 'prior image', projectId: project.id });
    const priorIteration = await prisma.iteration.findFirst({ where: { projectId: project.id, seq: 1 } });
    cleanup.iterationIds.push(priorIteration!.id);
    const priorBytes = await fs.readFile(resolveWorkspacePath(prior.imagePath));

    generateImage.mockRejectedValueOnce(new Error('simulated OpenAI failure'));

    await expect(client.generateImage({ prompt: 'this will fail', projectId: project.id })).rejects.toThrow(
      'simulated OpenAI failure'
    );

    const afterFailure = await prisma.iteration.findMany({ where: { projectId: project.id } });
    expect(afterFailure).toHaveLength(1);
    expect(afterFailure[0].id).toBe(priorIteration!.id);

    const priorBytesAfter = await fs.readFile(resolveWorkspacePath(prior.imagePath));
    expect(priorBytesAfter.equals(priorBytes)).toBe(true);

    const failureFile = resolveWorkspacePath(`projects/${project.id}/iterations/iter-2.png`);
    await expect(fs.access(failureFile)).rejects.toThrow();
  });
});

// ---------------------------------------------------------------------------
// Unknown project (defensive check)
// ---------------------------------------------------------------------------

describe('createRealImageVisionClient -- unknown project', () => {
  it('throws without writing a file or calling the imaging client', async () => {
    const generateImage = vi.fn();
    const client = createRealImageVisionClient({ generateImage, versioning: spyVersioning() });

    await expect(client.generateImage({ prompt: 'x', projectId: -1 })).rejects.toThrow(/no Project with id -1/);
    expect(generateImage).not.toHaveBeenCalled();
  });
});
